name: 'Virtualized Android Emulator'
on:
  workflow_dispatch:

  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Write OpenVPN config from secret
        run: |
          echo "${{ secrets.ANTARCTICA_DEV_OPENVPN_FILE }}" > client.ovpn
          echo "=== Checking original config content (first few lines) ==="
          head -n 5 client.ovpn
          
          # Add DNS resolution settings at the beginning of the file
          sed -i '1i script-security 2\nup /etc/openvpn/update-systemd-resolved\ndown /etc/openvpn/update-systemd-resolved' client.ovpn
          

      - name: Start OpenVPN
        run: |
          
          echo "=== Starting OpenVPN ==="
          sudo openvpn --config client.ovpn --daemon --log /tmp/openvpn.log --writepid /tmp/openvpn.pid


      - name: Validate VPN Connecction
        run: |
          if resolvectl status | grep -q "Link.*(tun0)"; then
            echo "Success: tun0 interface is configured correctly in systemd-resolved."
            exit 0
          else
            echo "Error: tun0 interface not found in resolvectl status."
            exit 1
          fi



          

        